name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: pnpm install, build
        run: |
          npx pnpm i
          npx pnpm run build
      - name: run Lighthouse CI
        run: |
          npx pnpm add -g @lhci/cli@0.8.x
          lhci autorun
